server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081/
          Predicates:
            - Path=/authenticate/**
        - id: dev-issue-book
          uri: http://localhost:8082/
          Predicates:
            - Path=/dib/**
