server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: http://localhost:8081/
          Predicates:
            - Path=/authenticate/**
        - id: dev-issue-book
          uri: http://localhost:8082/
          Predicates:
            - Path=/dib/**
            
logging:
  level:
    org.springframework: DEBUG

jwt:
  secret: mySecretKey
  expireMs: 120000
  refrEshexpireMs: 120000
